FROM node:lts-alpine
WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install --legacy-peer-deps --no-audit --no-fund --omit=dev

WORKDIR /usr/src/app/output
COPY apps/api/output/package.json ./
RUN npm install --legacy-peer-deps --no-audit --no-fund --omit=dev

WORKDIR /usr/src/app
COPY apps/api/output/ ./output

CMD ["node", "./output"]
