log:
  level: TRACE
  format: json

api:
  dashboard: true
  debug: true
  insecure: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"
    http:
      tls:
        certResolver: letsencrypt
        domains:
          - main: "january.sh"
            sans:
              - "*.january.sh"
  tcpsecure:
    address: ":4443"

certificatesResolvers:
  letsencrypt:
    acme:
      email: "admin@january.sh"
      storage: "/letsencrypt/acme.json"
      dnsChallenge:
        provider: hetzner

providers:
  http:
    endpoint: "http://api:3000/containers/discovery"

experimental:
  plugins:
    sablier:
      modulename: "github.com/sablierapp/sablier"
      version: "v1.8.1"
