name: Publish VSCode

on:
  workflow_dispatch:
  push:
    branches: [main]
    tags:
      - 'release/*'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    if: false
    # if: success() && startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Cache Or Restore Node Modules
        id: cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install --no-audit --no-fund

      - name: Build Prod
        run: nx release --skip-publish

      - uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_STATUS_WEBHOOK }}
          nodetail: true
          title: 'Publish VSCode ${{github.repository}}'
          url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
      - name: Publish
        run: npm run deploy
        env:
          VSCE_PAT: ${{ secrets.VSCODE_EXT_TOKEN }}
